/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitest_Jclass */

#ifndef _Included_com_example_jnitest_Jclass
#define _Included_com_example_jnitest_Jclass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitest_Jclass
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest_Jclass_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
