/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fmod_FmodUtils */

#ifndef _Included_com_example_fmod_FmodUtils
#define _Included_com_example_fmod_FmodUtils
#ifdef __cplusplus
extern "C" {
#endif

#define MODE_NORMAL 0
#define MODE_LUOLI 1
#define MODE_DASHU 2
#define MODE_JINGSONG 3
#define MODE_GAOGUAI 4
#define MODE_KONGLING 5
/*
 * Class:     com_example_fmod_FmodUtils
 * Method:    playsound
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_fmod_FmodUtils_playsound
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
